export {default as Home} from "./Home.jsx"
export {default as Contact} from "./Contact.jsx"
export { default as Faq } from "./Faq.jsx"
export { default as ServicesPage } from "./ServicesPage.jsx"
export { default as About } from "./About.jsx"