export {default as Home} from "./Home"
export {default as Contact} from "./Contact"
export { default as Faq } from "./Faq"
export { default as ServicesPage } from "./ServicesPage"
export { default as About } from "./About"